// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzVRbhg5NJy4wGTOuZO37vnXLUDpqvu2o',
    appId: '1:706855041316:web:756a1c21400730cb611bb1',
    messagingSenderId: '706855041316',
    projectId: 'fooddeliveryapp-c800d',
    authDomain: 'fooddeliveryapp-c800d.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-c800d.firebasestorage.app',
    measurementId: 'G-S5HQSXKGVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhVMSnAm9-ePmaQJINnz4OSi96LPe-ysc',
    appId: '1:706855041316:android:bcd415eb23d6b42d611bb1',
    messagingSenderId: '706855041316',
    projectId: 'fooddeliveryapp-c800d',
    storageBucket: 'fooddeliveryapp-c800d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWYEhUhKZ8r5BlntNaN46LlCTgR3WsDT8',
    appId: '1:706855041316:ios:f3fa53609a3d633a611bb1',
    messagingSenderId: '706855041316',
    projectId: 'fooddeliveryapp-c800d',
    storageBucket: 'fooddeliveryapp-c800d.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryAppWBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWYEhUhKZ8r5BlntNaN46LlCTgR3WsDT8',
    appId: '1:706855041316:ios:f3fa53609a3d633a611bb1',
    messagingSenderId: '706855041316',
    projectId: 'fooddeliveryapp-c800d',
    storageBucket: 'fooddeliveryapp-c800d.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryAppWBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzVRbhg5NJy4wGTOuZO37vnXLUDpqvu2o',
    appId: '1:706855041316:web:8dfae0218c8ff695611bb1',
    messagingSenderId: '706855041316',
    projectId: 'fooddeliveryapp-c800d',
    authDomain: 'fooddeliveryapp-c800d.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-c800d.firebasestorage.app',
    measurementId: 'G-1HV7TK311H',
  );
}
